### ISSUE TITLE
Clothes Switch broken when FaceEmo Prefab is added to the avatar

### ISSUE THREAD

**Issue by blufish1234** [suzuryg/face-emo#14] opened 2023-08-10 11:08 UTC
I have Write defaults ticked in my FX layer and I only added single animations for the switches for my clothes (As shown in the attachment below)
<img width="407" alt="image" src="https://github.com/suzuryg/face-emo/assets/97332474/c8ca431a-9c19-429c-852f-0bc122c8668b">
This broke when I applied Face Emo
Is this a bug?

**Comment by suzuryg** [comment] 2023-08-10 11:50
Please select the "FaceEmoPrefab" inside the avatar and enable the "Match Avatar Write Defaults" option in ModularAvatar. This might resolve the issue.
https://modular-avatar.nadena.dev/docs/reference/merge-animator/

However, please note that VRChat recommends the WriteDefaults to be set to OFF. Therefore, I have not fully tested the behavior of FaceEmo with WriteDefaults ON. This might introduce issues with FaceEmo's facial expressions.

**Comment by blufish1234** [comment] 2023-08-10 12:22
This worked when both of these FX has WD enabled! It may be a better idea to add a option to enable write defaults in the editor menu or setting menu.

**Comment by suzuryg** [comment] 2023-08-10 12:25
Thank you for the report! I'll consider adding that option.

**Comment by blufish1234** [comment] 2023-08-10 12:47
Edit: Since that option in Modular Avatar obeys the Avatar's WD state, maybe just leave that option on, no more to need to add options to enable or disable in the editor or settings menu

**Comment by suzuryg** [comment] 2023-08-10 12:57
I think that enabling WriteDefaults might introduce issues with FaceEmo's facial expressions. When activating the option, I would like to inform the users about this potential risk.

Moreover, I think that any issues arising from applying FaceEmo with the option disabled can be resolved by simply deleting the FaceEmoPrefab, so it shouldn't be much of a concern.

**Comment by blufish1234** [comment] 2023-08-10 13:15
I think that there may be a misinterpretation. 
What I meant is to leave this option on (shown below):
<img width="408" alt="image" src="https://github.com/suzuryg/face-emo/assets/97332474/5cfa2998-054f-4a47-8eb2-284b409af96f">
What this does is matches the WD state of the Animator to merge with the Avatar's FX layer. For example, if the avatar's FX layer does have WD on, then the Animator to merge's WD state would also be on, and vice versa.

**Comment by suzuryg** [comment] 2023-08-10 13:20
The AnimatorController for FaceEmo is designed with the assumption of WD being OFF. Therefore, if WD is set to ON to match the avatar, I'm concerned that the facial expressions might not transition smoothly. For instance, the previous expression might persist due to WD.

**Comment by blufish1234** [comment] 2023-08-10 13:38
As far as in my case, I haven't seen any issues with WD on. Anyway, thanks for helping out! Also I would like to ask that if this will be solved in the future updates? (shown below)
<img width="551" alt="image" src="https://github.com/suzuryg/face-emo/assets/97332474/10805dbb-e06e-454b-ba93-fb0376655c0e">

**Comment by suzuryg** [comment] 2023-08-10 13:43
Thank you for informing me that no issues have arisen! For the time being, I'd like to keep it as an option. However, if we can confirm that there are no problems, I'm considering setting it to match the avatar by default.

Regarding the dance gimmick, it's not a bug but a feature, and I haven't come up with an alternative solution yet...

**Comment by blufish1234** [comment] 2023-08-10 14:04
I think that not being able to change clothes when MMD dancing might be a big issue for people, which means it should be fixed as soon as possible. However, that's not urgent (at least for me ). It is also understandable because this is a brand new thing for managing face expressions in a simpler and easier way. Keep up the good work and take your time to solve that issue! >w<

**Closed** 2023-08-10 17:57 UTC
