### ISSUE TITLE
WD設定が正しく扱われていない // WD setting is not handled correctly

### ISSUE THREAD

**Issue by GotoFinal** [suzuryg/face-emo#101] opened 2023-12-30 18:41 UTC
こちらの日本語はすべてGPT-4を使用して書かれています。

現在のところ原因が分かりませんが、私のアバターの一つでジェスチャーがいつの間にかリセットされなくなっています。WDがオフのように振る舞っていますが、リセットアニメーションが存在せず、私のアニメーションが重なってしまっています。このツールは、すべてのジェスチャーで使用されるすべてのブレンドシェイプが正しくリセットされるようにする必要があります。
私のすべてのアニメーションは以前にEmoFaceツールを使用せずに作成され、WDのオン・オフに関わらずCGEで問題なく動作していました。

https://github.com/suzuryg/face-emo/assets/6942692/fa690dc1-5983-40f2-8a30-be9a2991af12

Not sure what is causing the issue right now, but currently in one of my avatars the gestures don't seems to be reset at any point, they are behaving like WD is off but no reset animation is present, so my animations stack on top of each other. The tool should ensure that all blendshapes used in all gestures are correctly reset.
All my animations were created before without using EmoFace tools and worked fine with CGE for both WD on and off.

**Comment by suzuryg** [comment] 2023-12-31 04:51
Thank you for your report. The reset animation is located in the following location, can you check the animation?

"FaceEmoPrefab" inside the avatar -> "MA Merge Animator" -> "FaceEmo_FX" -> "[USER EDIT] DEFAULT FACE" layer -> "DEFAULT" state animation

**Comment by GotoFinal** [comment] 2024-01-07 00:28
I used workaroud for now where i added random animation with write defaults on to the animator to force the FaceEmo to also use WD. But if I don't do that then the reset animation is just empty or conteins only the objects i toggle on/off
![image](https://github.com/suzuryg/face-emo/assets/6942692/5aa5f596-1746-4eb1-932c-e3cc2c5e82f8)

**Comment by suzuryg** [comment] 2024-01-09 17:38
That's strange... essentially, FaceEmo generates a reset animation for all blendshapes in the face mesh.
Is the list of face blendshapes visible in FaceEmo's expression editor?
If not, FaceEmo may not be finding the face mesh.

**Comment by GotoFinal** [comment] 2024-01-09 18:06
It's visible. But I do use a bit weird setup, so maybe its messing something up... As my face mesh is actually on different object. Also my animation files contains references to other face meshes that are not used so i can use single setup for all of my avatars.
The currently used face is setup inside the VRC avatar descriptor and FaceEmo correctly sees it on edit window:  (on other avatars I have multiple head objects, but only one is used at the time and the rest removed during build, EmoFace still works perfectly fine with that - except this issue)
![image](https://github.com/suzuryg/face-emo/assets/6942692/534d4bfc-3ad5-45bb-9d60-c575780ce566)
![image](https://github.com/suzuryg/face-emo/assets/6942692/92fa8f52-abf7-46b0-9f84-bfde8d2e547a)

**Comment by suzuryg** [comment] 2024-01-09 18:38
I understand about your avatar setup.
I moved the face mesh to a location other than directly under the avatar as a test, but I can't reproduce the problem...
Are you doing anything special during the build process? (e.g. changing the object hierarchy)

**Comment by GotoFinal** [comment] 2024-01-09 21:54
Hmm, interesting, my project changed a lot sience posting about that, and currently it does not happen either... well a lot changed including updating stuff like MA, so i guess you can just close this issue. Maybe it was related to the #73 as I often fail to save because of that... Tried to actually see if I can fix that, but it looks a bit more annoying

**Comment by GotoFinal** [comment] 2024-01-09 22:21
I've found this: https://stackoverflow.com/a/65019906 and based on that I made a small POC that seems to work, I made a PR so we can talk about that solution there: #104 
But feel free to close this issue unless you think there might be actually something more to it.

**Comment by suzuryg** [comment] 2024-01-11 18:15
I understand about the issue not recurring.
I will close this issue once, but if it recurs, please reopen this one and let's discuss.

**Closed by suzuryg** 2024-01-11 18:15 UTC
